/**
 * Profile snapshots — issue #98 (phase 3), implementing the snapshot half of
 * #19: before any ordering / preset change is applied, the profile's
 * composition-critical files are captured as a timestamped snapshot; a failed
 * or unwanted change can be rolled back in one step.
 *
 * A snapshot is a single JSON document under `<profile>/.dsh-market/
 * snapshots/<timestamp>-<seq>.json` holding the exact bytes of the files that
 * define the profile's composition: package.json (dependency + bundle list),
 * cordis.patch.yml (the user patch layer) and state.json (market disable
 * list + groups). Restoring validates every path (no traversal, no absolute
 * paths — same discipline as backup.ts) and writes all files from memory, so
 * a mid-restore failure cannot leave a half-written profile.
 */

import { dirname, join } from 'node:path'
import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { logEvent } from './log.ts'

const SNAPSHOT_DIR = join('.dsh-market', 'snapshots')

/**
 * Snapshot ids are generated by nextSnapshotId and must never be attacker-
 * shaped: anything else (paths, '..', absolute paths) is refused BEFORE it
 * reaches the filesystem, so restoreSnapshot/deleteSnapshot cannot escape the
 * snapshots directory (issue #98 review B3 — same discipline as backup.ts).
 */
const SNAPSHOT_ID_RE = /^snapshot-[0-9A-Za-z-]+$/

function validSnapshotId(id: string): boolean {
  return SNAPSHOT_ID_RE.test(id)
}

/** The files a snapshot captures, relative to the profile directory. */
const SNAPSHOT_FILES = ['package.json', 'cordis.patch.yml', '.dsh-market/state.json'] as const

interface SnapshotFile {
  path: string
  /** JSON documents keep their parsed form (re-serialized on restore). */
  json?: unknown
  /** Line-oriented text files (cordis.patch.yml) keep their lines. */
  lines?: string[]
}

export interface ProfileSnapshot {
  /** Snapshot id: the file basename without the .json suffix. */
  id: string
  createdAt: number
  files: SnapshotFile[]
}

/** Absolute snapshot directory for a profile. */
function snapshotDir(profileDir: string): string {
  return join(profileDir, SNAPSHOT_DIR)
}

function snapshotFile(profileDir: string, id: string): string {
  if (!validSnapshotId(id)) throw new Error('invalid snapshot id / 无效的快照 id')
  return join(snapshotDir(profileDir), `${id}.json`)
}

/** Basename of the next snapshot (timestamp + sequence for same-ms saves). */
function nextSnapshotId(profileDir: string): string {
  const dir = snapshotDir(profileDir)
  let names: string[] = []
  try {
    names = readdirSync(dir)
  } catch { /* directory absent — no collisions */ }
  const now = new Date().toISOString().replace(/[:.]/g, '-')
  let seq = 0
  let id = `snapshot-${now}`
  while (names.includes(`${id}.json`)) {
    seq += 1
    id = `snapshot-${now}-${String(seq)}`
  }
  return id
}

/**
 * Capture the profile's composition files into a new snapshot. Never throws
 * for missing optional files (cordis.patch.yml / state.json may not exist);
 * a missing package.json is not a snapshot-able profile.
 */
export function createProfileSnapshot(profileDir: string): ProfileSnapshot | null {
  const packagePath = join(profileDir, 'package.json')
  let packageJson: unknown
  try {
    packageJson = JSON.parse(readFileSync(packagePath, 'utf8'))
  } catch {
    return null
  }
  const files: SnapshotFile[] = [{ path: 'package.json', json: packageJson }]
  for (const path of SNAPSHOT_FILES.slice(1)) {
    try {
      const text = readFileSync(join(profileDir, path), 'utf8')
      if (path.endsWith('.json')) files.push({ path, json: JSON.parse(text) })
      else files.push({ path, lines: text.split('\n') })
    } catch { /* optional file absent */ }
  }
  const id = nextSnapshotId(profileDir)
  const snapshot: ProfileSnapshot = { id, createdAt: Date.now(), files }
  mkdirSync(snapshotDir(profileDir), { recursive: true, mode: 0o700 })
  writeFileSync(snapshotFile(profileDir, id), `${JSON.stringify(snapshot, null, 2)}\n`)
  logEvent('info', 'snapshot', `created ${id} (${files.map(file => file.path).join(', ')})`)
  return snapshot
}

/** All snapshots for a profile, newest first. Invalid files are skipped. */
export function listSnapshots(profileDir: string): ProfileSnapshot[] {
  let names: string[]
  try {
    names = readdirSync(snapshotDir(profileDir)).filter(name => name.endsWith('.json'))
  } catch {
    return []
  }
  const snapshots: ProfileSnapshot[] = []
  for (const name of names) {
    try {
      const value = JSON.parse(readFileSync(snapshotFile(profileDir, name.slice(0, -5)), 'utf8')) as ProfileSnapshot
      if (value?.id !== undefined && Array.isArray(value.files)) snapshots.push(value)
    } catch { /* corrupt snapshot — skip */ }
  }
  return snapshots.sort((a, b) => b.createdAt - a.createdAt)
}

/**
 * Restore a snapshot's files into the profile. Every file path must be one of
 * the known composition files (traversal / absolute paths are refused before
 * anything is written); each file is written via a same-directory temp +
 * rename (atomic per file), and a failure mid-restore rolls the already-
 * written files back to their pre-restore contents, so the profile is never
 * left half-restored.
 * @returns the paths restored; an error result when the snapshot is unsafe,
 * unknown, or a write failed (with any partial writes rolled back).
 */
export function restoreSnapshot(profileDir: string, id: string): { ok: boolean; restored: string[]; error?: string } {
  if (!validSnapshotId(id)) {
    return { ok: false, restored: [], error: 'invalid snapshot id / 无效的快照 id' }
  }
  let snapshot: ProfileSnapshot
  try {
    snapshot = JSON.parse(readFileSync(snapshotFile(profileDir, id), 'utf8')) as ProfileSnapshot
  } catch {
    return { ok: false, restored: [], error: 'snapshot not found / 快照不存在' }
  }
  const allowed = new Set<string>(SNAPSHOT_FILES)
  for (const file of snapshot.files) {
    if (typeof file.path !== 'string' || !allowed.has(file.path) || file.path.includes('..')) {
      return { ok: false, restored: [], error: `unsafe snapshot path: ${String(file.path)} / 快照路径不安全` }
    }
  }
  // Materialize every target + its current content FIRST, so a rollback can
  // restore the pre-restore bytes even if the profile already changed.
  const writes: Array<{ target: string; content: string; previous: string | null }> = []
  for (const file of snapshot.files) {
    const target = join(profileDir, file.path)
    const content = file.json !== undefined
      ? `${JSON.stringify(file.json, null, 2)}\n`
      : Array.isArray(file.lines) ? `${file.lines.join('\n')}` : ''
    let previous: string | null = null
    try {
      previous = readFileSync(target, 'utf8')
    } catch { /* target did not exist before */ }
    writes.push({ target, content, previous })
  }
  const restored: string[] = []
  try {
    for (const write of writes) {
      mkdirSync(dirname(write.target), { recursive: true })
      const temp = `${write.target}.tmp-${process.pid}-${Date.now()}-${String(restored.length)}`
      writeFileSync(temp, write.content)
      renameSync(temp, write.target)
      restored.push(write.target)
    }
  } catch (error) {
    // Roll back everything already written to its pre-restore bytes.
    for (const write of writes) {
      try {
        if (write.previous !== null) writeFileSync(write.target, write.previous)
        else rmSync(write.target, { force: true })
      } catch { /* best-effort rollback */ }
    }
    logEvent('error', 'snapshot', `restore ${id} failed and was rolled back: ${error instanceof Error ? error.message : String(error)}`)
    return { ok: false, restored: [], error: error instanceof Error ? error.message : String(error) }
  }
  logEvent('info', 'snapshot', `restored ${id}: ${restored.join(', ')}`)
  return { ok: true, restored: snapshot.files.map(file => file.path) }
}

/** Delete one snapshot; true only when it existed and was removed. */
export function deleteSnapshot(profileDir: string, id: string): boolean {
  if (!validSnapshotId(id)) return false
  const file = snapshotFile(profileDir, id)
  if (!existsSync(file)) return false
  try {
    rmSync(file)
    return true
  } catch {
    return false
  }
}
